-- Metrics Tables for Analytics
-- Created for pb_github_cicd_demo

CREATE TABLE IF NOT EXISTS SALES_METRICS (
    ID NUMBER AUTOINCREMENT PRIMARY KEY,
    METRIC_NAME VARCHAR(255) NOT NULL,
    METRIC_VALUE DECIMAL(18, 2),
    METRIC_DATE DATE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS MARKETING_METRICS (
    ID NUMBER AUTOINCREMENT PRIMARY KEY,
    METRIC_NAME VARCHAR(255) NOT NULL,
    METRIC_VALUE DECIMAL(18, 2),
    METRIC_DATE DATE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS PRODUCT_METRICS (
    ID NUMBER AUTOINCREMENT PRIMARY KEY,
    METRIC_NAME VARCHAR(255) NOT NULL,
    METRIC_VALUE DECIMAL(18, 2),
    METRIC_DATE DATE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
