CREATE TABLE SALES_METRICS (
    SALES_METRIC_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    METRIC_DATE DATE NOT NULL,
    REGION VARCHAR(100),
    PRODUCT_CATEGORY VARCHAR(100),
    TOTAL_REVENUE NUMBER(18,2),
    UNITS_SOLD NUMBER,
    AVERAGE_ORDER_VALUE NUMBER(18,2),
    DISCOUNT_AMOUNT NUMBER(18,2),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
