CREATE TABLE MARKETING_METRICS (
    MARKETING_METRIC_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    METRIC_DATE DATE NOT NULL,
    CAMPAIGN_NAME VARCHAR(200),
    CHANNEL VARCHAR(100),
    IMPRESSIONS NUMBER,
    CLICKS NUMBER,
    CONVERSIONS NUMBER,
    SPEND NUMBER(18,2),
    COST_PER_CLICK NUMBER(18,4),
    CONVERSION_RATE NUMBER(10,4),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
