CREATE TABLE PRODUCT_METRICS (
    PRODUCT_METRIC_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    METRIC_DATE DATE NOT NULL,
    PRODUCT_ID VARCHAR(50),
    PRODUCT_NAME VARCHAR(200),
    INVENTORY_COUNT NUMBER,
    UNITS_SOLD NUMBER,
    RETURN_COUNT NUMBER,
    AVERAGE_RATING NUMBER(3,2),
    REVIEW_COUNT NUMBER,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
